- become: true
  gather_facts: false
  hosts: all
  name: Prepare
  roles:
  - role: buluma.bootstrap
  - role: buluma.repo_epel
    when:
    - (ansible_distribution == "Amazon" and ansible_distribution_major_version ==
      "2") or (ansible_os_family == "RedHat" and ansible_distribution_major_version
      in [ "7", "8" ])
  - role: buluma.ca_certificates
