---
- name: Verify
  hosts: all
  become: true
  gather_facts: true

  tasks:
    - name: Ensure Fathom is responding on the specified port.
      ansible.builtin.uri:
        url: "http://127.0.0.1:9000"
        status_code: 200
      register: result
      until: result.status == 200
      retries: 60
      delay: 1

    - name: Check if connection still works
      ansible.builtin.ping:
