---
- name: Verify
  hosts: all
  become: yes
  gather_facts: yes

  tasks:
    - name: ensure Fathom is responding on the specified port.
      ansible.builtin.uri:
        url: "http://127.0.0.1:{{ fathom_http_port }}"
        status_code: 200
      register: result
      until: result.status == 200
      retries: 60
      delay: 1

    - name: check if connection still works
      ansible.builtin.ping:
